<div class="border" style="padding: 100px; margin: 100px">
<h4>Rules of the Game:</h4>
 
<p>To win the game, you must score the highest # of points.  Points are awarded when you answer each trivia question correctly. Points are deducted if you answer a bonus question incorrectly.</p>
 
<p>The game consists of 3 multiple choice questions and 1 bonus question with 3 clues.  Each multiple choice question is worth 100 points each if answered correctly.  </p>

<p>The bonus question is optional. The screen will ask you if you want to answer the bonus question before it is revealed. The bonus question requires you to input an answer into a dialog box.  It is not multiple choice. You will be awarded 200 points, if you answer the bonus question correctly using no clues.  If you use 1 clue and answer the bonus question correctly, you will only be awarded 150 points.  If you use 2 clues and answer the bonus question correctly, you will only be awarded 100 points. If you use all 3 clues and answer the bonus question correctly, you will only be awarded 50 points. If you answer the bonus question incorrectly, regardless of the number of clues you use, your point total will be reduced by 200 points.  Remember, you don't have to answer the bonus question.</p>
 
<p>You will have 3 minutes of game play to answer all the 3 multiple choice questions and the bonus question, if you choose to answer it.  If 2 or more players are tied for the highest score at the end of 3 minutes, then a tie-breaking session is introduced.  We ask 1 more question during the tie-breaking session (it also requires you to input an answer - it is not multiple choice).  If 2 or more players are still tied after the tie-breaking session, we introduce a second and, if necessary, a third tie-breaking session.  Each tie-breaking question is 100 points and you will have 30 seconds to answer each tie-breaking question. If 2 or more players are still tied for the highest score after the 3rd tie-breaking session, then all the tied players win.</p>

<p><a href="javascript: history.back()">back</a></p>

</div>
