<!DOCTYPE html>
<html lang="en">
<head>
   <title>Shadow and Act Films :: Admin</title>
   <link rel="stylesheet" type="text/css" href="/css/admin/style.css"/>
   <link rel="stylesheet" type="text/css" href="/js/jquery-ui-1.9.0.custom/css/smoothness/jquery-ui-1.9.0.custom.css"/>

   <script type="text/javascript" src="/js/jquery-1.8.2.js"></script>
   <script type="text/javascript" src="/js/jquery-ui-1.9.0.custom/js/jquery-ui-1.9.0.custom.js"></script>
</head>

<body>

   <h2>Shadow and Act Films Movie Trivia :: Admin </h2>
   <?php include 'includes/adminheader.php' ?>

   <div id="container">
      <?php echo $this->layout()->content; ?>
   </div>

</body>
