<!DOCTYPE html>
<html lang="en">
<head>
   <title>Shadow and Act Films</title>
   <link rel="stylesheet" type="text/css" href="/css/style.css"/>
   <link rel="stylesheet" type="text/css" href="/js/countdown/jquery.countdown.css"/>
   <link rel="stylesheet" type="text/css" href="/js/jquery-ui-1.9.0.custom/css/smoothness/jquery-ui-1.9.0.custom.css"/>

   <script type="text/javascript" src="/js/jquery-1.8.2.js"></script>
   <script type="text/javascript" src="/js/jquery-ui-1.9.0.custom/js/jquery-ui-1.9.0.custom.js"></script>
   <script type="text/javascript" src="/js/countdown/jquery.countdown.js"></script>
   <script type="text/javascript" src="/js/timer.js"></script>
</head>

<body>

<?php echo $this->layout()->content; ?>

</body>

</html>
